In [4]:
print("Hello \n World!")

Hello 
 World!


In [5]:
int(1.0)

1

In [6]:
bool(1)

True

In [9]:
x=4

In [10]:
x

4

In [22]:
print("ommair \\ ishaque")

ommair \ ishaque


In [23]:
Numbers="0123456"
Numbers[::2]

'0246'

In [24]:
"0123456".find('1')

1

In [25]:
'1'+'2'

'12'

In [26]:
A=[1,2,3,4,5]

In [27]:
help(A)

Help on list object:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __le__(self, value, /

In [2]:
A=(0,1,2,3)

In [3]:
#help(A)
A[3]

3

In [11]:
S={'A','B','C'}
S.add(1)
print(S)

{'C', 1, 'B', 'A'}


In [4]:
Dict={"A":1,"B":"2","C":[3,3,3],"D":(4,4,4),'E':5,'F':6}

In [5]:
Dict['D']

(4, 4, 4)

In [10]:
def artistname(*names):
    for name in names:
        print(name)
artistname('a','b','c')
artistname('aa','bb')

a
b
c
aa
bb


In [11]:
def thriller():
    date = 1984
    return date

thriller()

1984

In [13]:
#date

In [ ]:
def g(c):
    for i in c:
        i
    return 

In [14]:
def f(*c):

    return sum(c)

In [16]:
f(1,3,4)

8

In [20]:
class omm(object):
    def __init__(self, radius, color):
        self.radius=radius
        self.color=color


In [21]:
cc=omm(2,'red')

In [23]:
cc.radius

2

In [24]:
cc.color

'red'

# CLASS in PYTHON

In [41]:
class Restaurant(object):
    def __init__(self, restaurant_name, cuisine_type):
        self.restaurant_name = restaurant_name
        self.cuisine_type = cuisine_type
        
    def describe_restaurant(self):
        print("restaurant name : ", self.restaurant_name.title())
        print("cuisine_type : ", self.cuisine_type.title())
    
    def open_restaurant(self):
        print("Timing : ", " Mon-Fri 11:00 am 10:00 pm",  "    Sat & Sun 11:00 am 12:00 pm")

In [42]:
my_restaurant = Restaurant('Lala', 'Asian')

In [43]:
print("name " + my_restaurant.restaurant_name, "   cuisine " , my_restaurant.cuisine_type)

name Lala    cuisine  Asian


In [44]:
my_restaurant.describe_restaurant()

restaurant name :  Lala
cuisine_type :  Asian


In [45]:
my_restaurant.open_restaurant()

Timing :   Mon-Fri 11:00 am 10:00 pm     Sat & Sun 11:00 am 12:00 pm


In [46]:
A=['1','2','3']

for a in A:

    print(2*a)

11
22
33


In [53]:
def Delta(x):

    if x==0:

        y=1

    else:

        y=0

    return(y)

In [61]:
for i in range(0,10,1):
    Delta(i)
    print(i)

0
1
2
3
4
5
6
7
8
9


In [62]:
Delta(0)

1

In [11]:
path="C:/Users/ommair/Documents/PythonCourses/Data_analysis_in_python/toy_lab_ind_ebl_grp.csv"
file1 = open(path,'r')
file1.close()

In [18]:
path="C:/Users/ommair/Documents/PythonCourses/Data_analysis_in_python/toy_lab_ind_ebl_grp.csv"
with open(path,'r') as file2:
    stuff= file2.read(40)
    stuff2= file2.read(40)
    stuff3=file2.readline()
    print(stuff)
    print(stuff2)
    print(stuff3)

IDNum,IDStud,pbl8,ebl8,Lab01PrelabQuiz,L
ab02PrelabQuiz,Lab03PrelabQuiz,Lab04Prel
abQuiz,Lab05PrelabQuiz,Lab06PrelabQuiz,Lab07PrelabQuiz,Lab08PrelabQuiz,Lab09PrelabQuizProjectDay,Lab10PrelabQuiz,Lab01RE,Lab02RE,Lab03RE,Lab04RE,Lab05RE,Lab06RE,Lab07RE,Lab08RE,Lab09REProjectDay,Lab10RE,PeerEvaluation01,PeerEvaluation02,PeerEvaluation03,PeerEvaluation04,PeerEvaluation05,PeerEvaluation06,PeerEvaluation07,PeerEvaluation08,PeerEvaluation09,PeerEvaluation10,PeerEvaluation11,PeerEvaluation12,PeerEvaluation13,Lab01MarshmallowChallenge,Lab02PatternsofMotionandEquilibrium,Lab03NewtonsLawsofMotion,Lab04Collisions,Lab05Buoyancy,Lab06Calorimetry,Lab07SoundWaves,Lab08ReflectionandRefractionofLight,Lab09ProjectDay,Lab10PlanetWalkandearthsmagneticfield,FinalScore



In [19]:
import pandas as banana

df=banana.DataFrame({'a':[11,21,31],'b':[21,22,23]})

df.head()

a   b
0  11  21
1  21  22
2  31  23

In [2]:
import numpy as np
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [4]:
A= np.array([[11,12,13],[21,22,23],[31,32,33]])

In [6]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
A[0][1]

12

In [7]:
A[0:2,2]

array([13, 23])

In [8]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [9]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [10]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [20]:
A='1234567'

In [21]:
A[1::2]

'246'

In [24]:
A=((11,12),[21,22])
A[0][1]

12

In [27]:
A=[1,'a'] 
B=[2,1,'d']
A+B

[1, 'a', 2, 1, 'd']

In [28]:
V={'A','B'}
V.add('C')

In [29]:
A=['1','2','3']

for a in A:

    print(2*a)

11
22
33


In [30]:
def Add(x,y):

    z=y+x

    return(y)

In [31]:
Add('1','1')

'1'